"""empty message

Revision ID: 039568f154b0
Revises: None
Create Date: 2016-06-15 06:32:30.965626

"""

# revision identifiers, used by Alembic.
revision = '039568f154b0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('description', sa.String(length=1024), nullable=True))
    op.drop_column('plugin', 'download_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('download_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('plugin', 'description')
    ### end Alembic commands ###
