"""empty message

Revision ID: 4c52542edde0
Revises: 51a58255ddd4
Create Date: 2016-05-30 05:34:17.210657

"""

# revision identifiers, used by Alembic.
revision = '4c52542edde0'
down_revision = '51a58255ddd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('left_id', sa.String(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['plugin.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    ### end Alembic commands ###
