"""empty message

Revision ID: 52cf73b61658
Revises: 9d8e152a8516
Create Date: 2016-05-28 06:45:26.323938

"""

# revision identifiers, used by Alembic.
revision = '52cf73b61658'
down_revision = '9d8e152a8516'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('game', sa.String(), nullable=True))
    op.add_column('server', sa.Column('server_type', sa.String(), nullable=True))
    op.add_column('server', sa.Column('size', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'size')
    op.drop_column('server', 'server_type')
    op.drop_column('server', 'game')
    ### end Alembic commands ###
