"""empty message

Revision ID: 733b9f70b4a2
Revises: None
Create Date: 2016-12-18 12:20:25.451559

"""

# revision identifiers, used by Alembic.
revision = '733b9f70b4a2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'name')
    ### end Alembic commands ###
