"""empty message

Revision ID: 97f5e75f5e41
Revises: None
Create Date: 2016-12-06 12:41:31.213963

"""

# revision identifiers, used by Alembic.
revision = '97f5e75f5e41'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcpe_server',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('op', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('nice_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('server_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('left_id', sa.String(length=255), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['plugin.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('plugin')
    op.drop_table('mcpe_server')
    ### end Alembic commands ###
