"""empty message

Revision ID: 9d8e152a8516
Revises: dbfadcad20b7
Create Date: 2016-05-27 05:27:35.720974

"""

# revision identifiers, used by Alembic.
revision = '9d8e152a8516'
down_revision = 'dbfadcad20b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.drop_column(u'server', 'hashed_server_key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'server', sa.Column('hashed_server_key', sa.VARCHAR(), nullable=True))
    op.drop_table('user')
    ### end Alembic commands ###
