"""empty message

Revision ID: 9e05b5a814fd
Revises: 4c52542edde0
Create Date: 2016-05-30 05:50:41.907391

"""

# revision identifiers, used by Alembic.
revision = '9e05b5a814fd'
down_revision = '4c52542edde0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('nice_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin', 'nice_name')
    ### end Alembic commands ###
