"""empty message

Revision ID: bbdcf7afb341
Revises: None
Create Date: 2017-01-02 19:50:15.543566

"""

# revision identifiers, used by Alembic.
revision = 'bbdcf7afb341'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factorio_server',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('op', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factorio_server')
    ### end Alembic commands ###
