"""empty message

Revision ID: d72bcb02a3b0
Revises: 52cf73b61658
Create Date: 2016-05-28 09:02:47.660399

"""

# revision identifiers, used by Alembic.
revision = 'd72bcb02a3b0'
down_revision = '52cf73b61658'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=True),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.Column('motd', sa.String(), nullable=True),
    sa.Column('server_port', sa.String(), nullable=True),
    sa.Column('memory_limit', sa.String(), nullable=True),
    sa.Column('gamemode', sa.String(), nullable=True),
    sa.Column('max_players', sa.String(), nullable=True),
    sa.Column('spawn_protection', sa.String(), nullable=True),
    sa.Column('level_name', sa.String(), nullable=True),
    sa.Column('level_type', sa.String(), nullable=True),
    sa.Column('announce_player_achievements', sa.String(), nullable=True),
    sa.Column('white_list', sa.String(), nullable=True),
    sa.Column('enable_query', sa.String(), nullable=True),
    sa.Column('enable_rcon', sa.String(), nullable=True),
    sa.Column('allow_flight', sa.String(), nullable=True),
    sa.Column('spawn_animals', sa.String(), nullable=True),
    sa.Column('spawn_mobs', sa.String(), nullable=True),
    sa.Column('force_gamemode', sa.String(), nullable=True),
    sa.Column('hardcore', sa.String(), nullable=True),
    sa.Column('pvp', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('generator_settings', sa.String(), nullable=True),
    sa.Column('level_seed', sa.String(), nullable=True),
    sa.Column('rcon_password', sa.String(), nullable=True),
    sa.Column('auto_save', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('properties')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('server_id', sa.VARCHAR(), nullable=True),
    sa.Column('server_name', sa.VARCHAR(), nullable=True),
    sa.Column('motd', sa.VARCHAR(), nullable=True),
    sa.Column('server_port', sa.VARCHAR(), nullable=True),
    sa.Column('memory_limit', sa.VARCHAR(), nullable=True),
    sa.Column('gamemode', sa.VARCHAR(), nullable=True),
    sa.Column('max_players', sa.VARCHAR(), nullable=True),
    sa.Column('spawn_protection', sa.VARCHAR(), nullable=True),
    sa.Column('level_name', sa.VARCHAR(), nullable=True),
    sa.Column('level_type', sa.VARCHAR(), nullable=True),
    sa.Column('announce_player_achievements', sa.VARCHAR(), nullable=True),
    sa.Column('white_list', sa.VARCHAR(), nullable=True),
    sa.Column('enable_query', sa.VARCHAR(), nullable=True),
    sa.Column('enable_rcon', sa.VARCHAR(), nullable=True),
    sa.Column('allow_flight', sa.VARCHAR(), nullable=True),
    sa.Column('spawn_animals', sa.VARCHAR(), nullable=True),
    sa.Column('spawn_mobs', sa.VARCHAR(), nullable=True),
    sa.Column('force_gamemode', sa.VARCHAR(), nullable=True),
    sa.Column('hardcore', sa.VARCHAR(), nullable=True),
    sa.Column('pvp', sa.VARCHAR(), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), nullable=True),
    sa.Column('generator_settings', sa.VARCHAR(), nullable=True),
    sa.Column('level_seed', sa.VARCHAR(), nullable=True),
    sa.Column('rcon_password', sa.VARCHAR(), nullable=True),
    sa.Column('auto_save', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_properties')
    ### end Alembic commands ###
