"""empty message

Revision ID: dbfadcad20b7
Revises: eddeb36d3017
Create Date: 2016-05-26 13:58:03.363289

"""

# revision identifiers, used by Alembic.
revision = 'dbfadcad20b7'
down_revision = 'eddeb36d3017'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('logentry',
    #sa.Column('id', sa.Integer(), nullable=False),
    #sa.Column('date', sa.DateTime(), nullable=True),
    #sa.Column('message', sa.String(), nullable=True),
    #sa.PrimaryKeyConstraint('id')
    #)
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('logentry')
    ### end Alembic commands ###
