"""empty message

Revision ID: eddeb36d3017
Revises: None
Create Date: 2016-05-26 07:11:34.879450

"""

# revision identifiers, used by Alembic.
revision = 'eddeb36d3017'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('progenitor_email', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'progenitor_email')
    ### end Alembic commands ###
