# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.CharField(default='7c6b1b97-6407-4f2d-9b28-2b2ebfefa975', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
