# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='region',
            field=models.CharField(choices=[('eu-west-1', 'eu-west-1'), ('us-east-1', 'us-east-1')], default='eu-west-1', max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(default='42c4cce9-daf2-4d19-bdcc-c99ebfcd39df', max_length=200, primary_key=True, serialize=False),
        ),
    ]
