# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0002_auto_20170715_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(default='90594e42-157f-40e3-bff5-502f20d733f9', max_length=200, primary_key=True, serialize=False),
        ),
    ]
