# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20170715_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('ark', 'ark')], default='ark', max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(default='bf9a137c-ad23-4b45-aaee-8d7300c674b3', max_length=200, primary_key=True, serialize=False),
        ),
    ]
