# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20170715_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(default='998ca188-28c0-41fd-98bb-54ae945c1a29', max_length=200, primary_key=True, serialize=False),
        ),
    ]
