# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20170716_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 16, 13, 39, 7, 542623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(default='5d98106a-0ab4-4bd0-b8f3-5f2b24b86114', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('ark', 'Ark: Survival Evolved')], default='ark', max_length=20),
        ),
    ]
