# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20170716_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 16, 13, 49, 41, 178874, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(default='0a733cb7-41b7-49a1-89ef-365c92ebb373', max_length=200, primary_key=True, serialize=False),
        ),
    ]
