# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-16 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_auto_20170716_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 16, 13, 51, 27, 126623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(default='351178b4-c8ec-47a9-9d84-13f97a17b074', max_length=200, primary_key=True, serialize=False),
        ),
    ]
