# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0011_auto_20170716_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 16, 14, 0, 5, 108575, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(default='ae0512c3-9d5c-4b7f-a046-26ba3ade392f', max_length=200, primary_key=True, serialize=False),
        ),
    ]
