# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_auto_20170716_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 16, 14, 50, 27, 46841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.CharField(default='f0320bfa-f18b-4862-9386-cecde2a74e3d', max_length=200, primary_key=True, serialize=False),
        ),
    ]
